# Generated by Django 4.1.2 on 2023-04-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maglumat', '0074_ishgarler_phone_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishgarler',
            name='phone_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
